/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Main from "./main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Krib</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/vercel.svg" />
        <link ref={"stylesheet"} rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
      </Head>
      <>
        <Main />
      </>
    </>
  );
}
