/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Buyer from "./buyer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Krib</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <>
        <Buyer />
      </>
    </>
  );
}
